/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_a;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author az
 */
public class AñadirCupon extends javax.swing.JFrame {

    /**
     * Creates new form AñadirCupon
     */
    public AñadirCupon() {
        initComponents();
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Porcentaje");
        jComboBox1.addItem("Monto Fijo");
    }
 
    private String obtenerRuta(){
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(this)== JFileChooser.APPROVE_OPTION) {
            return fileChooser.getSelectedFile().getAbsolutePath();
        }
        return null;
    }
    
    private ArrayList<Cupon> leer(String ruta) throws IOException, ParseException{
        ArrayList<Cupon> cuponesdescuento =new ArrayList<>();
        
        SimpleDateFormat[] formatosFecha = {
        new SimpleDateFormat("dd/MM/yyyy"),
        new SimpleDateFormat("MM/dd/yyyy"), // Para formato americano
        new SimpleDateFormat("yyyy/MM/dd"),
        new SimpleDateFormat("dd-MM-yyyy"),
        new SimpleDateFormat("MM-dd-yyyy"),
        new SimpleDateFormat("yyyy-MM-dd")
    };
        
        
       try(BufferedReader br = new BufferedReader(new FileReader(ruta))){
           String linea;
           while ((linea = br.readLine())!= null) {               
               String[] datos = linea.split("\\|");
               if(datos.length <4) continue;
               
               Cupon c= new Cupon();
               c.CodigoCupon = datos[0].trim();
               c.Valordescuento = Double.parseDouble(datos[1].trim());
               c.esPorcentaje = datos[2].trim().equalsIgnoreCase("Porcentaje");
               
               
               boolean fechaParseada = false;
            for (SimpleDateFormat formato : formatosFecha) {
                try {
                    c.Fechavencimiento = formato.parse(datos[3].trim());
                    fechaParseada = true;
                    break; // Si funciona, sal del bucle
                } catch (ParseException e) {
                    // Continúa con el siguiente formato
                }
            }
            
            if (!fechaParseada) {
                System.out.println("Fecha no válida en línea: " + linea);
                continue; // Omitir este cupón si la fecha no es válida
               
              
           }
             cuponesdescuento.add(c);
       }
       return cuponesdescuento;
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CargaMasiva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo ");

        jLabel2.setText("Valor ");

        jLabel3.setText("Tipo");

        jLabel4.setText("Vencimiento ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CargaMasiva.setText("Cargar desde CSV");
        CargaMasiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaMasivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField2)
                                            .addComponent(jComboBox1, 0, 106, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CargaMasiva)
                                    .addComponent(jButton1))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(CargaMasiva, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
           String codigo = jTextField1.getText();
            String valorStr = jTextField2.getText();
            String tipo = jComboBox1.getSelectedItem().toString();
            String fechaStr = jTextField3.getText(); 
            
         if (codigo.isEmpty() || valorStr.isEmpty() || fechaStr.isEmpty()) {
          JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
            } 
        double valor = Double.parseDouble(valorStr);
        if (valor <= 0) {
            JOptionPane.showMessageDialog(this, "El valor debe ser mayor a cero", "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
       Date fechaVencimiento=new java.text.SimpleDateFormat("dd/MM/yyyy").parse(fechaStr);
        if (fechaVencimiento.before(new Date())) {
         JOptionPane.showMessageDialog(this, "La fecha de vencimiento debe ser futura", "Error", JOptionPane.ERROR_MESSAGE);
          return;
            }
         boolean esPorcentaje = tipo.equals("Porcentaje");
            
            // Crear nuevo cupón
            Cupon nuevoCupon = new Cupon();
            nuevoCupon.CodigoCupon = codigo;
            nuevoCupon.Valordescuento = valor;
            nuevoCupon.esPorcentaje = esPorcentaje;
            nuevoCupon.Fechavencimiento = fechaVencimiento;
            
            // Agregar a la lista global
            Proyecto_A.cuponesdescuento.add(nuevoCupon);
            
            JOptionPane.showMessageDialog(this, "Cupón creado exitosamente");
        } catch (NumberFormatException ex) {
           JOptionPane.showMessageDialog(this, "El valor debe ser un numero valido","Error",JOptionPane.ERROR_MESSAGE);
        }
           catch(java.text.ParseException ex){
           JOptionPane.showMessageDialog(this, "Formato de fecha inválido (use dd/MM/yyyy)", "Error", JOptionPane.ERROR_MESSAGE); 
        }
        catch(Exception ex){
          JOptionPane.showMessageDialog(this, "Error al crear el cupón: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);  
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CargaMasivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaMasivaActionPerformed
        // TODO add your handling code here:
       
        try {
            String ruta = obtenerRuta();
            if (ruta != null) {
                ArrayList<Cupon> cupones = leer(ruta);
                Proyecto_A.cuponesdescuento.addAll(cupones);
                JOptionPane.showMessageDialog(this, 
                    "Se cargaron " + cupones.size() + " cupones", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); // Cierra la ventana después de cargar
            }
        } catch (IOException ex) {
            Logger.getLogger(AñadirCupon.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AñadirCupon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CargaMasivaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargaMasiva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

  
}
