/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_a;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author az
 */
public class UsuarioNuevo extends javax.swing.JFrame {
private Usuario usuario;
    /**
     * Creates new form UsuarioNuevo
     */
    public UsuarioNuevo() {
        initComponents();
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Administrador");
        jComboBox1.addItem("Vendedor");
    }
    
    public static List<Usuario> cargarUsuarioXML(String path){
        List<Usuario> usuarios =new ArrayList<>();
        try {
        
        DocumentBuilderFactory constructor = DocumentBuilderFactory.newInstance();
        DocumentBuilder lector = constructor.newDocumentBuilder();
        
        Document document = lector.parse(new File(path));
        document.getDocumentElement().normalize();
        
        NodeList nodos = document.getElementsByTagName("usuario");
        
        for (int i = 0; i <nodos.getLength(); i++) {
            Node nodo = nodos.item(i);
            
            if (nodo.getNodeType()== Node.ELEMENT_NODE) {
                Element elemento = (Element) nodo;
                
                String nombre = obtenerValorXML(elemento, "nombre");
                String usuario = obtenerValorXML(elemento, "usuario");
                String contraseña = obtenerValorXML(elemento, "contraseña");
                String rol = obtenerValorXML(elemento, "rol");
                
                if (nombre != null && usuario !=null && contraseña !=null && rol !=null) {
                Usuario u = new Usuario();
                u.nombre=nombre;
                u.usuario = usuario;
                u.password=contraseña;
                u.rol=rol.equals("Administrador")?"A":"V";
                
                usuarios.add(u);  
                }
            }
        }
        
    } catch (Exception ex) {
        Logger.getLogger(UsuarioNuevo.class.getName()).log(Level.SEVERE, null, ex);
    }
       return usuarios;
    }
     private static String obtenerValorXML(Element elemento, String tagName) {
        NodeList nodos = elemento.getElementsByTagName(tagName);
        if (nodos != null && nodos.getLength() > 0) {
            Node nodo = nodos.item(0);
            return nodo.getTextContent().trim();
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        CargaXML = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Password");

        jLabel3.setText("rol");

        jLabel4.setText("Usuario");

        jButton1.setText("crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CargaXML.setText("Cargar desde XML");
        CargaXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(520, 520, 520))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2)))
                        .addGap(3, 3, 3)
                        .addComponent(CargaXML)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(CargaXML))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Nombre=jTextField1.getText();
        String Password=jTextField2.getText();
        
        String rol=jComboBox1.getSelectedItem().toString();
        String Rol;
        if (rol.equals("Administrador")) {
            Rol = "A";
        } else {
            Rol = "V";
        }
        String Usuario=jTextField3.getText();
        
        if (validarPassword(Password)) {
            Usuario u=new Usuario();
            u.nombre = Nombre;
            u.password = Password;
            u.rol = Rol;
            u.usuario = Usuario;
            
            
        Proyecto_A.usuarios.add(u);
        
        JOptionPane.showMessageDialog(this, "Usuario creado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Recuerde que la contraseña debe contener minimo 6 caracteres, un numero, una letra mayuscula y una letra minuscula","ERROR",JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean validarPassword(String password){
        if (password.length()<6) {
            return false;
        }
        boolean tieneNumero=false;
        boolean tieneMayuscula=false;
        boolean tieneMinuscula=false;
        
        for (char c : password.toCharArray()) {
            if (Character.isDigit(c)) {
                tieneNumero=true;
            } else if (Character.isUpperCase(c)) {
                tieneMayuscula = true;
            } else if (Character.isLowerCase(c)) {
                tieneMinuscula = true;
            }
            
        }
        return tieneNumero && tieneMayuscula && tieneMinuscula;
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CargaXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaXMLActionPerformed
        // TODO add your handling code here:
        
        String rutaXML ="usuario.xml";
        List<Usuario> usuarios = cargarUsuarioXML(rutaXML);
        
        if (!usuarios.isEmpty()) {
            Proyecto_A.usuarios.addAll(usuarios);
             JOptionPane.showMessageDialog(this, 
            "Se cargaron " + usuarios.size() + " usuarios desde XML", 
            "Carga exitosa", JOptionPane.INFORMATION_MESSAGE);
             this.dispose();
        }
        
    }//GEN-LAST:event_CargaXMLActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargaXML;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    
}
